# Generated by Django 4.2 on 2024-02-05 08:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tweets", "0005_hashtag_tweets_likes_tweets_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweets",
            name="bookmarks",
            field=models.ManyToManyField(
                blank=True,
                related_name="bookmarked_tweets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
