# Generated by Django 4.2 on 2024-02-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0006_tweets_bookmarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweets",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="tweet_images/"),
        ),
    ]
