# Generated by Django 4.2 on 2024-02-06 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0007_tweets_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tweets",
            name="image",
        ),
        migrations.CreateModel(
            name="TweetImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="tweet_images/")),
                (
                    "tweet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="tweets.tweets",
                    ),
                ),
            ],
        ),
    ]
