# Generated by Django 4.2 on 2024-02-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0008_remove_tweets_image_tweetimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweets",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
